# Generated by Django 3.1.4 on 2020-12-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
