# Generated by Django 3.1.5 on 2021-01-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201215_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='nameTag',
            new_name='nameTags',
        ),
    ]
