# Generated by Django 3.1.5 on 2021-01-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210114_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='nameTags',
            new_name='name_Tag',
        ),
        migrations.RenameField(
            model_name='password',
            old_name='passwordStr',
            new_name='password_Str',
        ),
    ]
