# Generated by Django 3.1.5 on 2021-01-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210114_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='name_Tag',
            new_name='nameTag',
        ),
        migrations.RenameField(
            model_name='password',
            old_name='password_Str',
            new_name='passwordStr',
        ),
    ]
