# Generated by Django 3.1.5 on 2021-01-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210115_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='nameTag',
            new_name='name_Tag',
        ),
        migrations.RenameField(
            model_name='password',
            old_name='passwordStr',
            new_name='password_Str',
        ),
    ]
