# Generated by Django 3.1.5 on 2021-01-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210115_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='password',
            old_name='name_Tag',
            new_name='Name_Tag',
        ),
        migrations.RenameField(
            model_name='password',
            old_name='password_Str',
            new_name='Password_String',
        ),
    ]
